/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class games_stendhal_client_gui_X11KeyConfig */

#ifndef _Included_games_stendhal_client_gui_X11KeyConfig
#define _Included_games_stendhal_client_gui_X11KeyConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     games_stendhal_client_gui_X11KeyConfig
 * Method:    SetDetectableAutoRepeat
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_games_stendhal_client_gui_X11KeyConfig_SetDetectableAutoRepeat
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
