/*
 * GuildManager.java
 *
 * Created on April 11, 2007, 2:01 PM
 */

package games.stendhal.client.gui;

import games.stendhal.client.StendhalClient;
import games.stendhal.client.entity.User;
import javax.swing.JOptionPane;
import marauroa.common.game.RPAction;

/**
 *
 * @author  timothyb89
 */
public class GuildManager extends javax.swing.JFrame {
    
    /** Creates new form GuildManager */
    public GuildManager() {
	initComponents();
	client = StendhalClient.get();
    }
    
    private StendhalClient client;
    
    private User playerEntity;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        guildTextBoxCreate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        invitePlayerName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guild Management");
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14));
        jLabel1.setText("Stendhal Guild Management");

        guildTextBoxCreate.setText("Guild Name Here");
        guildTextBoxCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guildTextBoxCreateMouseClicked(evt);
            }
        });

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("<html>If you would like to join a guild, please talk to a member<br>in the guild you wish to join.");

        jButton2.setText("Leave Guild");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("<html>Click here to leave your current guild.");

        invitePlayerName.setText("Player Name");

        jButton3.setText("Invite");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Invite a player to a guild you are in or have created.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guildTextBoxCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(invitePlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guildTextBoxCreate, invitePlayerName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guildTextBoxCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invitePlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {guildTextBoxCreate, invitePlayerName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	// creates the guild for the player
	String guild = playerEntity.getGuild();
	createGuild(guildTextBoxCreate.getText());
	JOptionPane.showMessageDialog(null, "You have created the guild \"" + guildTextBoxCreate.getText() + "\".");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	String guild = playerEntity.getGuild();
	inviteToGuild(invitePlayerName.getText(), guild);
	JOptionPane.showMessageDialog(null, "You have invited \"" + invitePlayerName.getText() + "\" to the \"" + guild + "\" guild.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	removeFromGuild("user");
	JOptionPane.showMessageDialog(null, "You have been removed from your old guild. You may now join a new one.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void guildTextBoxCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guildTextBoxCreateMouseClicked
	//erase text
	guildTextBoxCreate.setText("");
    }//GEN-LAST:event_guildTextBoxCreateMouseClicked
    
    
    /** 
     * Create guild
     */
    private void createGuild(String guildname) {
	if (client == null) {
	    /** If running standalone, just give an error */
	    JOptionPane.showMessageDialog(null, "It seems you are running this standalone. Please run it from the normal Stendhal game.");
	    return;
	}

	RPAction rpaction = new RPAction();
	rpaction.put("type", "createguild");
	rpaction.put("value", guildname);
	client.send(rpaction);
    }
    
    /**
     * Invite to guild
     */
    private void inviteToGuild(String user, String guildName) {
	if (client == null) {
	    // If running standalone, give an error
	    JOptionPane.showMessageDialog(null, "It seems that you are running this standalone. Please from it from the normal Stendhal game.");
	    return;
	}
	
	RPAction action = new RPAction();
	action.put("type", "inviteGuild");
	action.put("playername", user);
	action.put("guildname", guildName);
	client.send(action);
    }
    
    /** 
     *Remove player from guild
     */
    private void removeFromGuild(String user) { //we shouldn't seed that string, but.... 
	if (client == null) {
	    // If running standalone, give an error
	    JOptionPane.showMessageDialog(null, "It seems that you are running this standalone. Please from it from the normal Stendhal game.");
	    return;
	}
	 RPAction remove = new RPAction();
	 remove.put("type", "removeFromGuild");
	 //remove.put("", ""); //we don't need this. I'll just leave it here anyway...
	 client.send(remove);
	 
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new GuildManager().setVisible(true);
	    }
	});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guildTextBoxCreate;
    private javax.swing.JTextField invitePlayerName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    
}
