/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on 11.11.2007 05:53:06
 * Time to generate: 00:24.052 seconds
 *
 */

package games.stendhal.server.entity.npc.condition;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import utilities.PlayerTestHelper;
import utilities.SpeakerNPCTestHelper;

public class AllwaysTrueConditionTest {

	@Test
	public void testConstructor() throws Throwable {
		new AllwaysTrueCondition();
	}

	@Test
	public void testEquals() throws Throwable {
		assertFalse(new AllwaysTrueCondition().equals(null));

		AllwaysTrueCondition obj = new AllwaysTrueCondition();
		assertTrue(obj.equals(obj));

		assertFalse(new AllwaysTrueCondition().equals(new Integer(100)));

		assertTrue(new AllwaysTrueCondition().equals(new AllwaysTrueCondition()));
		assertFalse(new AllwaysTrueCondition().equals(new AllwaysTrueCondition() {
		}));
	}
	@Test
	public void testFire() throws Throwable {
		assertTrue(new AllwaysTrueCondition().fire(
				PlayerTestHelper.createPlayer(),
				"testAllwaysTrueConditionText",
				SpeakerNPCTestHelper.createSpeakerNPC()));
	}
	@Test
	public void testHashCode() throws Throwable {
		assertEquals(1, new AllwaysTrueCondition().hashCode());
	}
	@Test
	public void testToString() throws Throwable {
		assertEquals("true", new AllwaysTrueCondition().toString());
	}
}
