/***************************************************************************
 *                   (C) Copyright 2003-2011 - Stendhal                    *
 ***************************************************************************
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
package games.stendhal.server.core.rp.equipping.validator;

import games.stendhal.server.core.rp.equipping.EquipmentActionData;

/**
 * Ensures that there is not already an error generated by the builders
 * before validation begins.
 *
 * @author hendrik
 */
class NoErrorValidator implements Validator {

	public boolean validate(EquipmentActionData data) {
		return data.getErrorMessage() == null;
	}

}
