/* $Id$ */
/***************************************************************************
 *                   (C) Copyright 2003-2010 - Stendhal                    *
 ***************************************************************************
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
package games.stendhal.server.entity.npc.parser.testenv;

import games.stendhal.server.entity.npc.parser.ConversationParser;
import games.stendhal.server.entity.npc.parser.Expression;
import games.stendhal.server.entity.npc.parser.Sentence;

/**
 * Dialog of the NPC Conversation Parser Test Environment.
 * @author M. Fuchs
 */
@SuppressWarnings("serial")
public class TestEnvDlg extends javax.swing.JDialog {

    /** Creates new form TestEnvDlg */
    public TestEnvDlg() {
        initComponents();
        getRootPane().setDefaultButton(btOK);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOK;
    private javax.swing.JCheckBox cbMatching;
    private javax.swing.JLabel lbNormalized;
    private javax.swing.JLabel lbNumeral;
    private javax.swing.JLabel lbObject;
    private javax.swing.JLabel lbSentence;
    private javax.swing.JLabel lbSubject;
    private javax.swing.JLabel lbToString;
    private javax.swing.JLabel lbTrigger;
    private javax.swing.JLabel lbTrimmed;
    private javax.swing.JLabel lbVerb;
    private javax.swing.JTextField tfNormalized;
    private javax.swing.JTextField tfNumeral;
    private javax.swing.JTextField tfObject;
    private javax.swing.JComboBox tfSentence;
    private javax.swing.JTextField tfSubject;
    private javax.swing.JTextField tfToString;
    private javax.swing.JTextField tfTrigger;
    private javax.swing.JTextField tfTrimmed;
    private javax.swing.JTextField tfVerb;
    // End of variables declaration//GEN-END:variables

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSentence = new javax.swing.JLabel();
        tfSentence = new javax.swing.JComboBox();
        cbMatching = new javax.swing.JCheckBox();
        btOK = new javax.swing.JButton();
        tfTrimmed = new javax.swing.JTextField();
        lbTrimmed = new javax.swing.JLabel();
        lbNormalized = new javax.swing.JLabel();
        tfNormalized = new javax.swing.JTextField();
        lbToString = new javax.swing.JLabel();
        tfToString = new javax.swing.JTextField();
        lbTrigger = new javax.swing.JLabel();
        tfTrigger = new javax.swing.JTextField();
        lbSubject = new javax.swing.JLabel();
        tfSubject = new javax.swing.JTextField();
        lbNumeral = new javax.swing.JLabel();
        tfNumeral = new javax.swing.JTextField();
        lbObject = new javax.swing.JLabel();
        tfObject = new javax.swing.JTextField();
        lbVerb = new javax.swing.JLabel();
        tfVerb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NPC Parser Test Environment");
        setBounds(new java.awt.Rectangle(49, 200, 0, 0));
        setLocation(new java.awt.Point(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 480));

        lbSentence.setText("Please enter a sentence:");

        tfSentence.setEditable(true);
        tfSentence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "buy 3 cookies", "buy seven bananas", "give a bottle of wine", "buy enhanced lion shield", "Would you like to have an ice cream?", "Mary has a little lamb.", "I and you, he and they", "What is the an answer to life, the universe and everything?", "to be or not to be", "Take these three grilled steaks and have fun!", "99 red ballons", "Hi, how are you?", "_Hi, how are you?" }));
        tfSentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSentenceActionPerformed(evt);
            }
        });

        cbMatching.setText("for parsing");
        cbMatching.setActionCommand("for matching");
        cbMatching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatchingActionPerformed(evt);
            }
        });

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        tfTrimmed.setEditable(false);

        lbTrimmed.setText("Normalized:");

        lbNormalized.setText("Trimmed:");

        tfNormalized.setEditable(false);

        lbToString.setText("toString():");

        tfToString.setEditable(false);

        lbTrigger.setText("Trigger text:");

        tfTrigger.setEditable(false);

        lbSubject.setText("Subject:");

        tfSubject.setEditable(false);

        lbNumeral.setText("Numeral:");

        tfNumeral.setEditable(false);

        lbObject.setText("Object:");

        tfObject.setEditable(false);

        lbVerb.setText("Verb:");

        tfVerb.setEditable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbSentence)
                            .add(tfSentence, 0, 397, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cbMatching)
                        .add(4, 4, 4)
                        .add(btOK)
                        .add(26, 26, 26))
                    .add(lbNormalized)
                    .add(tfNormalized, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .add(lbTrimmed)
                    .add(tfTrimmed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .add(lbToString)
                    .add(tfToString, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .add(lbTrigger)
                    .add(tfTrigger, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbSubject)
                            .add(lbNumeral))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(tfNumeral)
                            .add(tfSubject, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(31, 31, 31)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbVerb)
                            .add(lbObject))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tfVerb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .add(tfObject, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lbSentence)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tfSentence, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btOK)
                    .add(cbMatching))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbNormalized)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(tfNormalized, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbTrimmed)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tfTrimmed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lbToString)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tfToString, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbTrigger)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tfTrigger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbSubject)
                    .add(tfSubject, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tfVerb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbVerb))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbNumeral)
                    .add(tfNumeral, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbObject)
                    .add(tfObject, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(269, 269, 269))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
    	Object selected = tfSentence.getSelectedItem().toString();

    	if (selected != null)
            processSentence(selected.toString());
    	else
            processSentence("");
    }//GEN-LAST:event_btOKActionPerformed

    private void tfSentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSentenceActionPerformed
        btOKActionPerformed(evt);
    }//GEN-LAST:event_tfSentenceActionPerformed

    private void cbMatchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatchingActionPerformed
        btOKActionPerformed(evt);
    }//GEN-LAST:event_cbMatchingActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
                new TestEnvDlg().setVisible(true);
//            }
//        });
    }

	private void processSentence(String text) {
		Sentence sentence;

		boolean forParsing = cbMatching.isSelected();

		if (forParsing)
			sentence = ConversationParser.parseForMatching(text);
		else
			sentence = ConversationParser.parse(text);

		tfTrimmed.setText(sentence.getTrimmedText());

        tfNormalized.setText(sentence.getNormalized());

        tfToString.setText(sentence.toString());

        tfTrigger.setText(sentence.getTriggerExpression().toString());

        String subj = sentence.getSubjectName();
        tfSubject.setText(subj!=null? subj: null);

        String verb = sentence.getVerbString();
        tfVerb.setText(verb!=null? verb: "");

        Expression num = sentence.getNumeral();
        tfNumeral.setText(num!=null? num.getNormalized(): "");

        String obj = sentence.getObjectName();
        tfObject.setText(obj!=null? obj: "");
	}
}
